version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: amrit-demo-docker
        LoadBalancerInfo:
          ContainerName: amrit-laravel
          ContainerPort: 80
